<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            'Web Development',
            'Mobile App Development',
            'UI/UX Design',
            'Graphic Design',
            'Logo Design',
            'Content Writing',
            'SEO Optimization',
            'Digital Marketing',
            'Social Media Management',
            'Video Editing',
            'Animation',
            'Voice Over',
            'Translation',
            'Data Entry',
            'Virtual Assistant',
            'Project Management',
            'Business Consulting',
            'Accounting',
            'Legal Consulting',
            'Photography',
            'Videography',
            'Illustration',
            '3D Modeling',
            'Game Development',
            'Software Testing',
            'Cybersecurity',
            'Cloud Computing',
            'DevOps',
            'Machine Learning',
            'Artificial Intelligence',
            'Blockchain Development',
            'E-commerce Development',
            'WordPress Development',
            'Shopify Development',
            'Python Programming',
            'Java Programming',
            'JavaScript Programming',
            'PHP Programming',
            'C++ Programming',
            'C# Programming',
            'Ruby Programming',
            'Swift Programming',
            'Kotlin Programming',
            'Flutter Development',
            'React Native Development',
            'React.js Development',
            'Vue.js Development',
            'Angular Development',
            'Node.js Development',
            'Laravel Development',
            'Django Development',
            'Spring Boot Development',
            'ASP.NET Development',
            'Database Management',
            'SQL',
            'NoSQL',
            'Data Analysis',
            'Data Science',
            'Big Data',
            'Excel',
            'PowerPoint',
            'Public Speaking',
            'Teaching',
            'Tutoring',
            'Music Production',
            'Audio Editing',
            'Scriptwriting',
            'Copywriting',
            'Proofreading',
            'Editing',
            'Research',
            'Market Research',
            'Sales',
            'Customer Service',
            'Lead Generation',
            'Email Marketing',
            'Affiliate Marketing',
            'Influencer Marketing',
            'Brand Strategy',
            'Public Relations',
            'Event Planning',
            'Interior Design',
            'Fashion Design',
            'Product Design',
            'Industrial Design',
            'Architecture',
            'Civil Engineering',
            'Mechanical Engineering',
            'Electrical Engineering',
            'Electronics Engineering',
            'Chemical Engineering',
            'Biomedical Engineering',
            'Environmental Engineering',
            'Petroleum Engineering',
            'Aerospace Engineering',
            'Marine Engineering',
            'Automotive Engineering',
            'Robotics',
            'Mechatronics',
            'Telecommunications',
            'Network Administration',
            'System Administration',
            'IT Support',
            'Help Desk',
            'Technical Writing',
            'Grant Writing',
            'Resume Writing',
            'Cover Letter Writing',
            'LinkedIn Profile Optimization',
            'Career Coaching',
            'Life Coaching',
            'Fitness Training',
            'Yoga Instruction',
            'Nutrition Counseling',
            'Mental Health Counseling',
            'Psychology',
            'Sociology',
            'History',
            'Geography',
            'Political Science',
            'Economics',
            'Finance',
            'Investing',
            'Real Estate',
            'Stock Trading',
            'Forex Trading',
            'Cryptocurrency Trading',
        ];

        foreach ($skills as $skill) {
            Skill::firstOrCreate(['name' => $skill]);
        }
    }
}
